nanorq: nanorq_block_symbols
nanorq_block_symbols()
uint16_t nanorq_block_symbols (nanorq * rq, uint8_t sbn)
Definition at line 382 of file nanorq.c.
References partition::IL, partition::IS, partition::JL, partition::JS, and nanorq::src_part.
Referenced by dump_block(), main(), nanorq_block_decoder(), nanorq_block_encoder(), nanorq_encoder_max_repair(), and nanorq_num_missing().
{
     if (sbn < rq->src_part.JL)
         return rq->src_part.IL;
     if (sbn - rq->src_part.JL < rq->src_part.JS)
         return rq->src_part.IS;
     return 0;
 }