nanorq: nanorq_generate_symbols
nanorq_generate_symbols()
bool nanorq_generate_symbols (nanorq * rq, uint8_t sbn, struct ioctx * io)
Definition at line 186 of file nanorq.c.
References oti_common::Al, nanorq::common, get_source_block(), get_symbol_offset(), pparams::H, partition::IL, partition::IS, pparams::K_padded, nanorq_block_encoder(), encoder_core::num_symbols, om_A, om_destroy(), OM_INITIAL, om_resize(), source_block::part, source_block::part_tot, precode_matrix_gen(), precode_matrix_intermediate1(), encoder_core::prm, ioctx::read, octmat::rows, pparams::S, ioctx::seek, encoder_core::symbol_size, and encoder_core::symbolmat.
Referenced by main(), and nanorq_encode().
{
     octmat A = OM_INITIAL, D = OM_INITIAL;
     struct encoder_core *enc = nanorq_block_encoder(rq, sbn);
     struct pparams *prm = NULL;
     if (enc == NULL)
         return false;
     if (enc->symbolmat.rows > 0)
         return true;
     prm = &enc->prm;
     precode_matrix_gen(prm, &A, 0);
     om_resize(&D, prm->K_padded + prm->S + prm->H,
               enc->symbol_size * rq->common.Al);
     uint16_t row = 0, col = 0;
     for (row = 0; row < prm->S + prm->H; row++) {
         for (col = 0; col < D.cols; col++) {
             om_A(D, row, col) = 0;
         }
     }
     struct source_block blk = get_source_block(rq, sbn, enc->symbol_size);
     for (; row < prm->S + prm->H + enc->num_symbols; row++) {
         uint32_t symbol_id = row - (prm->S + prm->H);
         col = 0;
         for (uint16_t i = 0; i < enc->symbol_size;) {
             size_t offset = get_symbol_offset(&blk, i, enc->num_symbols, symbol_id);
             uint16_t sublen = (i < blk.part_tot) ? blk.part.IL : blk.part.IS;
             uint16_t stride = sublen * rq->common.Al;
             uint8_t buf[stride];
             i += sublen;
             size_t got = 0;
             if (io->seek(io, (const int) offset)) {
                 got = io->read(io, buf, stride);
             }
             for (int byte = 0; byte < got; byte++) {
                 om_A(D, row, col++) = buf[byte];
             }
             for (int byte = (int) got; byte < stride; byte++) {
                 om_A(D, row, col++) = 0;
             }
         }
     }
     for (; row < D.rows; row++) {
         for (uint16_t i = 0; i < D.cols; i++)
             om_A(D, row, i) = 0;
     }
     enc->symbolmat = precode_matrix_intermediate1(prm, &A, &D);
     if (enc->symbolmat.rows == 0)
         return false;
     om_destroy(&A);
     om_destroy(&D);
     return true;
 }