nanorq: get_symbol_offset
get_symbol_offset()
static size_t get_symbol_offset (struct source_block * blk, size_t pos, uint16_t K, uint32_t symbol_id) static
Definition at line 149 of file nanorq.c.
References source_block::al, partition::IL, partition::IS, source_block::part, source_block::part_tot, and source_block::sbloc.
Referenced by nanorq_decode_block(), nanorq_encode(), and nanorq_generate_symbols().
{
     size_t i;
     if (pos < blk->part_tot) {
         size_t sub_blk_id = pos / blk->part.IL;
         i = blk->sbloc + sub_blk_id * K * blk->part.IL + symbol_id * blk->part.IL +
             pos % blk->part.IL;
     } else {
         size_t pos_part2 = pos - blk->part_tot;
         size_t sub_blk_id = pos_part2 / blk->part.IS;
         i = blk->sbloc + (blk->part_tot * K) + sub_blk_id * K * blk->part.IS +
             symbol_id * blk->part.IS + pos_part2 % blk->part.IS;
     }
     return i * blk->al;
 }