nanorq: nanorq_block_decoder
nanorq_block_decoder()
static struct decoder_core* nanorq_block_decoder (nanorq * rq, uint8_t sbn) static
Definition at line 465 of file nanorq.c.
References oti_common::Al, bitmask_new(), nanorq::common, nanorq::decoders, decoder_core::mask, nanorq_block_symbols(), decoder_core::num_symbols, om_resize(), params_init(), decoder_core::prm, decoder_core::sbn, decoder_core::symbol_size, decoder_core::symbolmat, and oti_common::T.
Referenced by nanorq_decode_block(), nanorq_decoder_add_symbol(), nanorq_num_missing(), and nanorq_num_repair().
{
     uint16_t num_symbols = nanorq_block_symbols(rq, sbn);
     uint16_t symbol_size = rq->common.T / rq->common.Al;
     if (rq->decoders[sbn])
         return rq->decoders[sbn];
     if (num_symbols == 0 || symbol_size == 0)
         return NULL;
     struct decoder_core *dec = calloc(1, sizeof(struct decoder_core));
     dec->sbn = sbn;
     dec->num_symbols = num_symbols;
     dec->symbol_size = symbol_size;
     dec->prm = params_init(num_symbols);
     dec->mask = bitmask_new(num_symbols);
     om_resize(&dec->symbolmat, num_symbols, symbol_size * rq->common.Al);
     rq->decoders[sbn] = dec;
     return dec;
 }