nanorq: om_destroy
om_destroy()
void om_destroy (octmat * v)
Definition at line 40 of file octmat.c.
References octmat::cols, octmat::cols_al, octmat::data, and octmat::rows.
Referenced by decode_phase3(), nanorq_decode_cleanup(), nanorq_encode(), nanorq_encode_cleanup(), nanorq_generate_symbols(), precode_matrix_decode(), precode_matrix_init_HDPC(), precode_matrix_intermediate1(), and precode_matrix_intermediate2().
{
     v->rows = 0;
     v->cols = 0;
     v->cols_al = 0;
     free(v->data);
     v->data = NULL;
 }