nanorq: om_resize
om_resize()
void om_resize (octmat * v, uint16_t r, uint16_t c)
Definition at line 12 of file octmat.c.
References octmat::cols, octmat::cols_al, octmat::data, OCTMAT_ALIGN, ozero(), and octmat::rows.
Referenced by decode_phase3(), nanorq_block_decoder(), nanorq_decoder_add_symbol(), nanorq_generate_symbols(), precode_matrix_decode(), precode_matrix_encode(), precode_matrix_gen(), precode_matrix_init_HDPC(), precode_matrix_intermediate1(), precode_matrix_intermediate2(), precode_matrix_make_GAMMA(), and precode_matrix_make_MT().
{
     v->rows = r;
     v->cols = c;
     void *aligned = NULL;
     v->cols_al = (uint16_t) ((c / OCTMAT_ALIGN + ((c % OCTMAT_ALIGN) ? 1 : 0)) * OCTMAT_ALIGN);
     if (posix_memalign(&aligned, OCTMAT_ALIGN, r * v->cols_al) != 0) {
         exit(ENOMEM);
     }
     ozero(aligned, 0, v->cols_al * r);
     v->data = (uint8_t *) aligned;
 }