nanorq: precode_matrix_intermediate2
precode_matrix_intermediate2()
bool precode_matrix_intermediate2 (octmat * M, octmat * A, octmat * D, struct pparams * prm, repair_vec * repair_bin, struct bitmask * mask, uint16_t num_symbols, uint16_t overhead)
Definition at line 412 of file precode.c.
References bitmask_check(), bitmask_gaps(), octmat::cols, decode_phase0(), ocopy(), om_destroy(), om_P, om_resize(), precode_matrix_encode(), precode_matrix_intermediate1(), and octmat::rows.
Referenced by precode_matrix_decode().
{
   uint16_t num_gaps, gap = 0, row = 0;
   octmat C;
   if (D->cols == 0) {
     return false;
   }
   decode_phase0(prm, A, mask, repair_bin, num_symbols, overhead);
   C = precode_matrix_intermediate1(prm, A, D);
   if (C.rows == 0) {
     return false;
   }
   num_gaps = (uint16_t) bitmask_gaps(mask, num_symbols);
   om_resize(M, num_gaps, D->cols);
   for (gap = 0; gap < num_symbols && num_gaps > 0; gap++) {
     if (bitmask_check(mask, gap))
       continue;
     octmat ret = precode_matrix_encode(prm, &C, gap);
     ocopy(om_P(*M), om_P(ret), row, 0, M->cols);
     om_destroy(&ret);
     row++;
     num_gaps--;
   }
   om_destroy(&C);
   return true;
 }