nanorq: decode_phase0
decode_phase0()
static void decode_phase0 (struct pparams * prm, octmat * A, struct bitmask * mask, repair_vec * repair_bin, uint16_t num_symbols, uint16_t overhead) static
Definition at line 123 of file precode.c.
References bitmask_check(), bitmask_gaps(), octmat::cols, pparams::H, pparams::K_padded, kv_A, kv_destroy, kv_size, pparams::L, om_A, params_get_idxs(), octmat::rows, and pparams::S.
Referenced by precode_matrix_intermediate2().
{
   size_t padding = prm->K_padded - num_symbols;
   uint16_t num_gaps = (uint16_t) bitmask_gaps(mask, num_symbols);
   uint16_t rep_idx = 0;
   for (uint16_t gap = 0; gap < prm->L && num_gaps > 0; gap++) {
     if (bitmask_check(mask, gap))
       continue;
     uint16_t row = gap + prm->H + prm->S;
     for (uint16_t col = 0; col < A->cols; col++) {
       om_A(*A, row, col) = 0;
     }
     uint16_vec idxs =
         params_get_idxs(prm, (uint32_t) (kv_A(*repair_bin, rep_idx++).esi + padding));
     for (int idx = 0; idx < kv_size(idxs); idx++) {
       om_A(*A, row, kv_A(idxs, idx)) = 1;
     }
     kv_destroy(idxs);
     num_gaps--;
   }
   uint16_t rep_row = (uint16_t)(A->rows - overhead);
   for (; rep_row < A->rows; rep_row++) {
     for (uint16_t col = 0; col < A->cols; col++) {
       om_A(*A, rep_row, col) = 0;
     }
     uint16_vec idxs =
         params_get_idxs(prm, (uint32_t) (kv_A(*repair_bin, rep_idx++).esi + padding));
     for (int idx = 0; idx < kv_size(idxs); idx++) {
       om_A(*A, rep_row, kv_A(idxs, idx)) = 1;
     }
     kv_destroy(idxs);
   }
 }