nanorq: decode_phase2
decode_phase2()
static bool decode_phase2 (octmat * A, octmat * D, uint16_t i, uint16_t u, uint16_t L) static
Definition at line 254 of file precode.c.
References octmat::cols, oaxpy(), OCTET_DIV, om_A, om_P, oscal(), and oswaprow().
Referenced by precode_matrix_intermediate1().
{
   uint16_t row_start = i, row_end = L;
   uint16_t col_start = A->cols - u;
   // FIXME: identify and swap dependent rows
   for (uint16_t row = row_start; row < row_end; row++) {
     uint16_t row_nonzero = row;
     uint16_t diag = col_start + (row - row_start);
     for (; row_nonzero < row_end; row_nonzero++) {
       if (om_A(*A, row_nonzero, diag) != 0) {
         break;
       }
     }
     if (row_nonzero == row_end) {
       fprintf(stderr, "FIXME: dependent row in A\n");
       return false;
     }
     if (row != row_nonzero) {
       oswaprow(om_P(*A), row, row_nonzero, A->cols);
       oswaprow(om_P(*D), row, row_nonzero, D->cols);
     }
     if (om_A(*A, row, diag) > 1) {
       uint8_t multiple = om_A(*A, row, diag);
       oscal(om_P(*A), row, A->cols, OCTET_DIV(1, multiple));
       oscal(om_P(*D), row, D->cols, OCTET_DIV(1, multiple));
     }
     for (uint16_t del_row = row_start; del_row < row_end; del_row++) {
       if (del_row == row)
         continue;
       uint8_t multiple = om_A(*A, del_row, diag);
       if (multiple == 0)
         continue;
       oaxpy(om_P(*A), om_P(*A), del_row, row, A->cols, multiple);
       oaxpy(om_P(*D), om_P(*D), del_row, row, D->cols, multiple);
     }
   }
   return true;
 }