nanorq: decode_phase3
decode_phase3()
static void decode_phase3 (octmat * A, octmat * X, octmat * D, uint16_t i) static
Definition at line 300 of file precode.c.
References octmat::cols, ogemm(), om_A, om_copy(), om_destroy(), OM_INITIAL, om_P, and om_resize().
Referenced by precode_matrix_intermediate1().
{
   octmat Xb = OM_INITIAL;
   octmat Ab = OM_INITIAL;
   octmat Db = OM_INITIAL;
   om_resize(&Xb, i, i);
   for (uint16_t row = 0; row < i; row++) {
     for (uint16_t col = 0; col < i; col++) {
       om_A(Xb, row, col) = om_A(*X, row, col);
     }
   }
   om_copy(&Ab, A);
   om_copy(&Db, D);
   ogemm(om_P(Xb), om_P(Ab), om_P(*A), i, i, Ab.cols);
   ogemm(om_P(Xb), om_P(Db), om_P(*D), i, i, Db.cols);
   om_destroy(&Ab);
   om_destroy(&Xb);
   om_destroy(&Db);
 }