nanorq: precode_matrix_decode
precode_matrix_decode()
bool precode_matrix_decode (struct pparams * prm, octmat * X, repair_vec * repair_bin, struct bitmask * mask)
Definition at line 459 of file precode.c.
References bitmask_check(), bitmask_gaps(), bitmask_set(), octmat::cols, pparams::H, pparams::K_padded, kv_A, kv_size, ocopy(), om_destroy(), OM_INITIAL, om_P, om_resize(), precode_matrix_gen(), precode_matrix_intermediate2(), repair_sym::row, octmat::rows, and pparams::S.
Referenced by nanorq_decode_block().
{
   uint16_t num_symbols = X->rows, rep_idx, num_gaps, num_repair, overhead;
   octmat A = OM_INITIAL;
   octmat D = OM_INITIAL;
   octmat M = OM_INITIAL;
   num_repair = (uint16_t) kv_size(*repair_bin);
   num_gaps = (uint16_t) bitmask_gaps(mask, num_symbols);
   if (num_gaps == 0)
     return true;
   if (num_repair < num_gaps)
     return false;
 AGAIN:
   overhead = num_repair - num_gaps;
   rep_idx = 0;
   precode_matrix_gen(prm, &A, overhead);
   om_resize(&D, prm->S + prm->H + prm->K_padded + overhead, X->cols);
   uint16_t skip = prm->S + prm->H;
   for (uint16_t row = 0; row < X->rows; row++) {
     ocopy(om_P(D), om_P(*X), skip + row, row, D.cols);
   }
   for (uint16_t gap = 0; gap < num_symbols && rep_idx < num_repair; gap++) {
     if (bitmask_check(mask, gap))
       continue;
     uint16_t row = skip + gap;
     struct repair_sym rs = kv_A(*repair_bin, rep_idx++);
     ocopy(om_P(D), om_P(rs.row), row, 0, D.cols);
   }
   for (uint16_t row = skip + prm->K_padded; rep_idx < num_repair; row++) {
     struct repair_sym rs = kv_A(*repair_bin, rep_idx++);
     ocopy(om_P(D), om_P(rs.row), row, 0, D.cols);
   }
   bool precode_ok = precode_matrix_intermediate2(&M, &A, &D, prm, repair_bin,
                                                  mask, num_symbols, overhead);
   om_destroy(&A);
   om_destroy(&D);
   /* FIXME
    * ugly hack to temporarily sweep decode failures under the rug
    */
   if (!precode_ok && overhead > 0) {
     num_repair--;
     goto AGAIN;
   }
   if (!precode_ok)
     return false;
   uint16_t miss_row = 0;
   for (uint16_t row = 0; row < num_symbols && miss_row < M.rows; row++) {
     if (bitmask_check(mask, row))
       continue;
     miss_row++;
     if (bitmask_check(mask, row))
       continue;
     ocopy(om_P(*X), om_P(M), row, (uint16_t) (miss_row - 1), X->cols);
     bitmask_set(mask, row);
   }
   om_destroy(&M);
   return true;
 }