nanorq: precode_matrix_intermediate1
precode_matrix_intermediate1()
octmat precode_matrix_intermediate1 (struct pparams * prm, octmat * A, octmat * D)
Definition at line 363 of file precode.c.
References octmat::cols, decode_phase1(), decode_phase2(), decode_phase3(), decode_phase4(), decode_phase5(), kv_A, kv_destroy, kv_init, kv_push, kv_resize, pparams::L, ocopy(), om_copy(), om_destroy(), OM_INITIAL, om_P, om_resize(), and octmat::rows.
Referenced by nanorq_generate_symbols(), and precode_matrix_intermediate2().
{
   bool success;
   uint16_t i, u;
   uint16_vec c;
   kv_init(c);
   octmat C = OM_INITIAL;
   octmat X = OM_INITIAL;
   if (prm->L == 0 || A == NULL || A->rows == 0 || A->cols == 0) {
     return C;
   }
   om_copy(&X, A);
   kv_resize(uint16_t, c, prm->L);
   for (uint16_t l = 0; l < prm->L; l++) {
     kv_push(uint16_t, c, l);
   }
   success = decode_phase1(prm, A, &X, D, c, &i, &u);
   if (!success) {
     kv_destroy(c);
     om_destroy(&X);
     return C;
   }
   success = decode_phase2(A, D, i, u, prm->L);
   if (!success) {
     kv_destroy(c);
     om_destroy(&X);
     return C;
   }
   decode_phase3(A, &X, D, i);
   om_destroy(&X);
   decode_phase4(A, D, i, u);
   decode_phase5(A, D, i);
   om_destroy(A);
   om_resize(&C, D->rows, D->cols);
   for (uint16_t l = 0; l < prm->L; l++) {
     ocopy(om_P(C), om_P(*D), kv_A(c, l), l, C.cols);
   }
   kv_destroy(c);
   return C;
 }