nanorq: nanorq_decode_cleanup
nanorq_decode_cleanup()
void nanorq_decode_cleanup (nanorq * rq, uint8_t sbn)
Definition at line 580 of file nanorq.c.
References bitmask_free(), nanorq::decoders, kv_A, kv_destroy, kv_size, decoder_core::mask, om_destroy(), decoder_core::repair_bin, decoder_core::sbn, and decoder_core::symbolmat.
Referenced by main(), and nanorq_free().
{
     if (rq->decoders[sbn]) {
         struct decoder_core *dec = rq->decoders[sbn];
         om_destroy(&dec->symbolmat);
         if (kv_size(dec->repair_bin) > 0) {
             for (uint16_t rs = 0; rs < kv_size(dec->repair_bin); rs++) {
                 om_destroy(&(kv_A(dec->repair_bin, rs).row));
             }
             kv_destroy(dec->repair_bin);
         }
         bitmask_free(dec->mask);
         free(dec);
         rq->decoders[sbn] = NULL;
     }
 }