nanorq: nanorq_encode
nanorq_encode()
uint64_t nanorq_encode (nanorq * rq, void * data, uint32_t esi, uint8_t sbn, struct ioctx * io)
Definition at line 398 of file nanorq.c.
References oti_common::Al, nanorq::common, get_source_block(), get_symbol_offset(), partition::IL, partition::IS, pparams::K_padded, nanorq_block_encoder(), nanorq_generate_symbols(), encoder_core::num_symbols, om_destroy(), om_P, source_block::part, source_block::part_tot, precode_matrix_encode(), encoder_core::prm, ioctx::read, octmat::rows, ioctx::seek, encoder_core::symbol_size, and encoder_core::symbolmat.
Referenced by dump_esi().
{
     uint64_t written = 0;
     struct encoder_core *enc = nanorq_block_encoder(rq, sbn);
     if (enc == NULL)
         return 0;
     if (esi < enc->num_symbols) {
         struct source_block blk = get_source_block(rq, sbn, enc->symbol_size);
         uint8_t *dst = ((uint8_t *) data);
         for (uint16_t i = 0; i < enc->symbol_size;) {
             size_t offset = get_symbol_offset(&blk, i, enc->num_symbols, esi);
             uint16_t sublen = (i < blk.part_tot) ? blk.part.IL : blk.part.IS;
             uint16_t stride = sublen * rq->common.Al;
             uint8_t buf[stride];
             i += sublen;
             int got = 0;
             if (io->seek(io, (const int) offset)) {
                 got = (int) io->read(io, buf, stride);
             }
             for (int byte = 0; byte < got; byte++) {
                 *dst = buf[byte];
                 dst++;
                 written++;
             }
             for (int byte = got; byte < stride; byte++) {
                 *dst = 0;
                 dst++;
                 written++;
             }
         }
     } else {
         // esi is for repair symbol
         struct pparams *prm = &enc->prm;
         if (enc->symbolmat.rows == 0) {
             bool generated = nanorq_generate_symbols(rq, sbn, io);
             if (!generated)
                 return 0;
         }
         uint32_t isi = esi + (prm->K_padded - enc->num_symbols);
         octmat tmp = precode_matrix_encode(prm, &enc->symbolmat, isi);
         uint8_t *dst = ((uint8_t *) data);
         uint8_t *octet = om_P(tmp);
         for (uint16_t i = 0; i < enc->symbol_size; i++) {
             for (int byte = 0; byte < rq->common.Al; byte++) {
                 *dst = (uint8_t) ((octet == NULL) ? 0 : *(octet++));
                 dst++;
                 written++;
             }
         }
         om_destroy(&tmp);
     }
     return written;
 }