nanorq: nanorq_block_encoder
nanorq_block_encoder()
static struct encoder_core* nanorq_block_encoder (nanorq * rq, uint8_t sbn) static
Definition at line 167 of file nanorq.c.
References oti_common::Al, nanorq::common, nanorq::encoders, nanorq_block_symbols(), encoder_core::num_symbols, params_init(), encoder_core::prm, encoder_core::sbn, encoder_core::symbol_size, and oti_common::T.
Referenced by nanorq_encode(), and nanorq_generate_symbols().
{
     uint16_t num_symbols = nanorq_block_symbols(rq, sbn);
     uint16_t symbol_size = rq->common.T / rq->common.Al;
     if (rq->encoders[sbn])
         return rq->encoders[sbn];
     if (num_symbols == 0 || symbol_size == 0)
         return NULL;
     struct encoder_core *enc = calloc(1, sizeof(struct encoder_core));
     enc->sbn = sbn;
     enc->num_symbols = num_symbols;
     enc->symbol_size = symbol_size;
     enc->prm = params_init(num_symbols);
     rq->encoders[sbn] = enc;
     return enc;
 }