nanorq: get_source_block
get_source_block()
static struct source_block get_source_block (nanorq * rq, uint8_t sbn, uint16_t symbol_size) static
Definition at line 130 of file nanorq.c.
References source_block::al, source_block::part, source_block::part_tot, and source_block::sbloc.
Referenced by nanorq_decode_block(), nanorq_encode(), and nanorq_generate_symbols().
{
     struct source_block ret;
     ret.part = rq->sub_part;
     ret.al = rq->common.Al;
     ret.sbloc = 0;
     ret.part_tot = rq->sub_part.IL * rq->sub_part.JL;
     if (sbn < rq->src_part.JL) {
         ret.sbloc = sbn * rq->src_part.IL * symbol_size;
     } else if (sbn - rq->src_part.JL < rq->src_part.JS) {
         ret.sbloc = (rq->src_part.IL * rq->src_part.JL) * symbol_size +
                     (sbn - rq->src_part.JL) * rq->src_part.IS * symbol_size;
     }
     return ret;
 }