nanorq: main
main()
int main (int argc, char ** argv)
Definition at line 65 of file encode.c.
References defaultPayloadName, ioctx::destroy, dump_block(), ioctx_from_file(), nanorq_blocks(), nanorq_encoder_new(), nanorq_free(), nanorq_generate_symbols(), nanorq_oti_common(), nanorq_oti_scheme_specific(), ioctx::size, and usage().
{
     if (argc < 2)
         usage(argv[0]);
     char *srcFilename = argv[1];
     char *packetSize = argc < 3 ? "600" : argv[2];
     char *filename = argc < 4 ? defaultPayloadName : argv[3];
     double expected_loss;
     if (argc < 5) {
         expected_loss = 6.0;
     } else {
         char *dummy;
         expected_loss = strtod(argv[4], &dummy);
     }
     int overhead;
     if (argc < 6) {
         overhead = (int) 5;
     } else {
         char *dummy;
         overhead = (int) strtol(argv[5], &dummy, 10);
     }
     struct ioctx *myio = NULL;
     {
         myio = ioctx_from_file(srcFilename, 1);
         if (!myio) {
             fprintf(stderr, "couldnt access file %s\n", srcFilename);
             return -1;
         }
     }
     nanorq *rq = NULL;
     {
         size_t filesize = myio->size(myio);
         // determine chunks, symbol size, memory usage from size
         uint16_t packet_size = (uint16_t) strtol(packetSize, NULL, 10); // T
         uint8_t align = 4;
         uint16_t ss = (uint16_t) (packet_size / 2);
         uint32_t ws = (uint32_t) (packet_size * 100);
         srand((unsigned int) time(0));
         rq = nanorq_encoder_new(filesize, packet_size, ss, align, ws);
         if (rq == NULL) {
             fprintf(stderr, "Coud not initialize encoder.\n");
             return -1;
         }
     }
     uint8_t num_sbn = 0;
     {
         num_sbn = nanorq_blocks(rq);
         for (uint8_t b = 0; b < num_sbn; b++) {
             nanorq_generate_symbols(rq, b, myio);
         }
     }
     {
         uint64_t oti_common = htobe64(nanorq_oti_common(rq));
         uint32_t oti_scheme = htobe32(nanorq_oti_scheme_specific(rq));
         FILE *oh = fopen(filename, "w+");
         fwrite(&oti_common, 1, sizeof(oti_common), oh);
         fwrite(&oti_scheme, 1, sizeof(oti_scheme), oh);
         for (uint8_t sbn = 0; sbn < num_sbn; sbn++) {
             dump_block(rq, myio, oh, sbn, expected_loss, overhead);
         }
         fclose(oh);
     }
     nanorq_free(rq);
     myio->destroy(myio);
     return 0;
 }