nanorq: nanorq_decode_block
nanorq_decode_block()
uint64_t nanorq_decode_block (nanorq * rq, struct ioctx * io, uint8_t sbn)
Definition at line 539 of file nanorq.c.
References oti_common::Al, nanorq::common, oti_common::F, get_source_block(), get_symbol_offset(), partition::IL, partition::IS, decoder_core::mask, nanorq_block_decoder(), om_R, source_block::part, source_block::part_tot, precode_matrix_decode(), decoder_core::prm, decoder_core::repair_bin, octmat::rows, ioctx::seek, decoder_core::symbol_size, decoder_core::symbolmat, and ioctx::write.
Referenced by main().
{
     uint64_t written = 0;
     struct decoder_core *dec = nanorq_block_decoder(rq, sbn);
     struct pparams *prm = &dec->prm;
     if (dec == NULL)
         return 0;
     bool success =
             precode_matrix_decode(prm, &dec->symbolmat, &dec->repair_bin, dec->mask);
     if (!success) {
         return 0;
     }
     uint16_t max_esi = dec->symbolmat.rows;
     uint16_t row = 0, col = 0;
     struct source_block blk = get_source_block(rq, sbn, dec->symbol_size);
     for (; row < max_esi; row++) {
         col = 0;
         for (uint16_t i = 0; i < dec->symbol_size;) {
             size_t offset = get_symbol_offset(&blk, i, max_esi, row);
             uint16_t sublen = (i < blk.part_tot) ? blk.part.IL : blk.part.IS;
             uint16_t stride = sublen * rq->common.Al;
             i += sublen;
             if (io->seek(io, (const int) offset)) {
                 uint16_t len = stride;
                 if (offset >= rq->common.F)
                     continue;
                 if ((offset + stride) >= rq->common.F) {
                     len = (uint16_t) (rq->common.F - offset);
                 }
                 written += io->write(io, om_R(dec->symbolmat, row) + col, len);
                 col += stride;
             }
         }
     }
     return written;
 }