nanorq: nanorq_free
nanorq_free()
void nanorq_free (nanorq * rq)
Definition at line 289 of file nanorq.c.
References nanorq_blocks(), nanorq_decode_cleanup(), and nanorq_encode_cleanup().
Referenced by main().
{
     uint8_t num_sbn = nanorq_blocks(rq);
     if (rq) {
         for (uint8_t sbn = 0; sbn < num_sbn; sbn++) {
             nanorq_encode_cleanup(rq, sbn);
             nanorq_decode_cleanup(rq, sbn);
         }
         free(rq);
     }
 }