nanorq: nanorq_num_missing
nanorq_num_missing()
uint32_t nanorq_num_missing (nanorq * rq, uint8_t sbn)
Definition at line 522 of file nanorq.c.
References bitmask_gaps(), decoder_core::mask, nanorq_block_decoder(), and nanorq_block_symbols().
Referenced by main().
{
     uint16_t num_symbols = nanorq_block_symbols(rq, sbn);
     struct decoder_core *dec = nanorq_block_decoder(rq, sbn);
     if (dec == NULL)
         return 0;
     return (uint32_t) bitmask_gaps(dec->mask, num_symbols);
 }