nanorq: precode_matrix_init_HDPC
precode_matrix_init_HDPC()
static void precode_matrix_init_HDPC (struct pparams * prm, octmat * A) static
Definition at line 86 of file precode.c.
References octmat::cols, pparams::H, pparams::K_padded, ogemm(), om_A, om_destroy(), OM_INITIAL, om_P, om_resize(), precode_matrix_make_GAMMA(), precode_matrix_make_MT(), octmat::rows, and pparams::S.
Referenced by precode_matrix_gen().
{
   uint16_t m = prm->H;
   uint16_t n = prm->K_padded + prm->S;
   if (m == 0 || n == 0)
     return;
   octmat MT = precode_matrix_make_MT(m, n);
   octmat GAMMA = precode_matrix_make_GAMMA(n);
   octmat MTxGAMMA = OM_INITIAL;
   om_resize(&MTxGAMMA, MT.rows, GAMMA.cols);
   ogemm(om_P(MT), om_P(GAMMA), om_P(MTxGAMMA), MT.rows, MT.cols, GAMMA.cols);
   size_t row, col;
   for (col = 0; col < GAMMA.cols; col++) {
     for (row = 0; row < MT.rows; row++) {
       om_A(*A, prm->S + row, col) = om_A(MTxGAMMA, row, col);
     }
   }
   om_destroy(&MT);
   om_destroy(&GAMMA);
   om_destroy(&MTxGAMMA);
 }