nanorq: precode_matrix_gen
precode_matrix_gen()
void precode_matrix_gen (struct pparams * prm, octmat * A, uint16_t overhead)
Definition at line 352 of file precode.c.
References pparams::B, pparams::H, pparams::L, om_resize(), pparams::P, precode_matrix_add_G_ENC(), precode_matrix_add_identity(), precode_matrix_init_HDPC(), precode_matrix_init_LDPC1(), precode_matrix_init_LDPC2(), pparams::S, and pparams::W.
Referenced by nanorq_generate_symbols(), and precode_matrix_decode().
{
   om_resize(A, prm->L + overhead, prm->L);
   precode_matrix_init_LDPC1(A, prm->S, prm->B);
   precode_matrix_add_identity(A, prm->S, 0, prm->B);
   precode_matrix_init_LDPC2(A, prm->W, prm->S, prm->P);
   precode_matrix_init_HDPC(prm, A);
   precode_matrix_add_identity(A, prm->H, prm->S, prm->L - prm->H);
   precode_matrix_add_G_ENC(prm, A);
 }