nanorq: precode_matrix_encode
precode_matrix_encode()
octmat precode_matrix_encode (struct pparams * prm, octmat * C, uint32_t isi)
Definition at line 446 of file precode.c.
References octmat::cols, kv_A, kv_destroy, kv_size, oaddrow(), OM_INITIAL, om_P, om_resize(), and params_get_idxs().
Referenced by nanorq_encode(), and precode_matrix_intermediate2().
{
   octmat ret = OM_INITIAL;
   om_resize(&ret, 1, C->cols);
   uint16_vec idxs = params_get_idxs(prm, isi);
   for (uint16_t idx = 0; idx < kv_size(idxs); idx++) {
     oaddrow(om_P(ret), om_P(*C), 0, kv_A(idxs, idx), ret.cols);
   }
   kv_destroy(idxs);
   return ret;
 }