nanorq: bitmask_check
bitmask_check()
bool bitmask_check (struct bitmask * bm, size_t id)
Definition at line 40 of file bitmask.c.
References IDXBITS, kv_A, and kv_size.
Referenced by decode_phase0(), nanorq_decoder_add_symbol(), precode_matrix_decode(), and precode_matrix_intermediate2().
{
     size_t idx = id / IDXBITS;
     if (idx >= kv_size(bm->mask))
         return false;
     uint32_t check_mask = (uint32_t) (1 << (id % IDXBITS));
     return (kv_A(bm->mask, idx) & check_mask) != 0;
 }