nanorq: params_get_idxs
params_get_idxs()
uint16_vec params_get_idxs (struct pparams * prm, uint32_t X)
Definition at line 112 of file params.c.
References ptuple::a, ptuple::a1, ptuple::b, ptuple::b1, ptuple::d, ptuple::d1, gen_tuple(), pparams::J, kv_init, kv_push, kv_resize, pparams::P, pparams::P1, and pparams::W.
Referenced by decode_phase0(), precode_matrix_add_G_ENC(), and precode_matrix_encode().
{
     uint16_vec ret;
     struct ptuple t = gen_tuple(X, prm->J, prm->W, prm->P1);
     kv_init(ret);
     kv_resize(uint16_t, ret, t.d + t.d1);
     kv_push(uint16_t, ret, t.b);
     for (uint16_t j = 1; j < t.d; j++) {
         t.b = (t.b + t.a) % prm->W;
         kv_push(uint16_t, ret, t.b);
     }
     while (t.b1 >= prm->P)
         t.b1 = (t.b1 + t.a1) % prm->P1;
     kv_push(uint16_t, ret, prm->W + t.b1);
     for (uint16_t j = 1; j < t.d1; j++) {
         t.b1 = (t.b1 + t.a1) % prm->P1;
         while (t.b1 >= prm->P)
             t.b1 = (t.b1 + t.a1) % prm->P1;
         kv_push(uint16_t, ret, prm->W + t.b1);
     }
     return ret;
 }