nanorq: gen_tuple
gen_tuple()
static struct ptuple gen_tuple (uint32_t X, uint16_t J, uint16_t W, uint16_t P1) static
Definition at line 59 of file params.c.
References ptuple::a, ptuple::a1, ptuple::b, ptuple::b1, ptuple::d, ptuple::d1, deg(), and rnd_get().
Referenced by params_get_idxs().
{
     struct ptuple ret;
     size_t A = (size_t) (53591 + J * 997);
     if (A % 2 == 0)
         A++;
     size_t B1 = (size_t) (10267 * (J + 1));
     uint32_t y = (uint32_t)((B1 + X * A));
     uint32_t v = rnd_get(y, 0, (uint32_t)((1 << 20)));
     ret.d = deg(v, W);
     ret.a = (uint16_t) (1 + (uint16_t)(rnd_get(y, 1, (const uint32_t) (W - 1))));
     ret.b = (uint16_t)(rnd_get(y, 2, W));
     if (ret.d < 4) {
         ret.d1 = (uint16_t) (2 + (uint16_t)(rnd_get(X, 3, 2)));
     } else {
         ret.d1 = 2;
     }
     ret.a1 = (uint16_t) (1 + (uint16_t)(rnd_get(X, 4, (const uint32_t) (P1 - 1))));
     ret.b1 = (uint16_t)(rnd_get(X, 5, P1));
     return ret;
 }