nanorq: ioctx_from_file
ioctx_from_file()
struct ioctx* ioctx_from_file (const char * fn, int t)
Definition at line 50 of file io.c.
References ioctx::destroy, fileio_destroy(), fileio_read(), fileio_seek(), fileio_size(), fileio_write(), fileioctx::fp, fileioctx::io, ioctx::read, ioctx::seek, ioctx::size, and ioctx::write.
Referenced by main().
{
   struct fileioctx *ret = NULL;
   FILE *fp;
   if (t) {
     fp = fopen(fn, "r");
   } else {
     fp = fopen(fn, "w+"); // create decoder
   }
   if (!fp)
     return NULL;
   ret = calloc(1, sizeof(struct fileioctx));
   ret->fp = fp;
   ret->io.read = fileio_read;
   ret->io.write = fileio_write;
   ret->io.seek = fileio_seek;
   ret->io.size = fileio_size;
   ret->io.destroy = fileio_destroy;
   return (struct ioctx *)ret;
 }