nanorq: bitmask_gaps
bitmask_gaps()
size_t bitmask_gaps (struct bitmask * bm, size_t until)
Definition at line 57 of file bitmask.c.
Referenced by decode_phase0(), nanorq_decoder_add_symbol(), nanorq_num_missing(), precode_matrix_decode(), and precode_matrix_intermediate2().
{
     size_t gaps = 0, idx;
     size_t until_idx = (until / IDXBITS);
     until_idx = (until_idx > kv_size(bm->mask)) ? kv_size(bm->mask) : until_idx;
     for (idx = 0; idx < until_idx; idx++) {
         uint32_t target = kv_A(bm->mask, idx);
         gaps += __builtin_popcountll(~target);
     }
     if (until % IDXBITS) {
         uint32_t until_mask = (uint32_t) ((1 << (until % IDXBITS)) - 1);
         uint32_t target = kv_A(bm->mask, idx) | ~until_mask;
         gaps += __builtin_popcountll(~target);
     }
     return gaps;
 }