nanorq: dump_block
dump_block()
void dump_block (nanorq * rq, struct ioctx * myio, FILE * oh, uint8_t sbn, double expected_loss, int OVERHEAD)
Definition at line 34 of file encode.c.
References dump_esi(), nanorq_block_symbols(), and nanorq_encode_cleanup().
Referenced by main().
{
     int overhead = OVERHEAD;
     uint32_t num_esi = nanorq_block_symbols(rq, sbn);
     int num_dropped = 0, num_rep = 0;
     for (uint32_t esi = 0; esi < num_esi; esi++) {
         float dropped = (float) rand() / (float) RAND_MAX * (float) 100.0;
         float drop_prob = (float) expected_loss;
         if (dropped < drop_prob) {
             num_dropped++;
         } else {
             dump_esi(rq, myio, oh, sbn, esi);
         }
     }
     for (uint32_t esi = num_esi; esi < num_esi + num_dropped + overhead; esi++) {
         dump_esi(rq, myio, oh, sbn, esi);
         num_rep++;
     }
     nanorq_encode_cleanup(rq, sbn);
     fprintf(stderr, "block %d is %d packets, dropped %d, created %d repair\n",
             sbn, num_esi, num_dropped, num_rep);
 }