nanorq: dump_esi
dump_esi()
void dump_esi (nanorq * rq, struct ioctx * myio, FILE * oh, uint8_t sbn, uint32_t esi)
Definition at line 17 of file encode.c.
References nanorq_encode(), nanorq_fid(), and nanorq_symbol_size().
Referenced by dump_block().
{
     uint32_t fid = htobe32(nanorq_fid(sbn, esi));
     uint16_t packet_size = nanorq_symbol_size(rq);
     uint8_t data[packet_size];
     uint64_t written = nanorq_encode(rq, (void *) data, esi, sbn, myio);
     if (written != packet_size) {
         fprintf(stderr, "failed to encode packet data for sbn %d esi %d.", sbn,
                 esi);
         abort();
     } else {
         fwrite(&fid, 1, sizeof(fid), oh);
         fwrite(data, 1, packet_size, oh);
     }
 }