nanorq: precode_matrix_make_MT
precode_matrix_make_MT()
static octmat precode_matrix_make_MT (uint16_t rows, uint16_t cols) static
Definition at line 51 of file precode.c.
References octmat::cols, OCT_EXP, om_resize(), rnd_get(), and octmat::rows.
Referenced by precode_matrix_init_HDPC().
{
   octmat MT = OM_INITIAL;
   om_resize(&MT, rows, cols);
   for (uint16_t row = 0; row < MT.rows; row++) {
     uint16_t col;
     for (col = 0; col < MT.cols - 1; col++) {
       uint32_t tmp = rnd_get(col + 1, 6, MT.rows);
       if ((row == tmp) ||
           (row == (tmp + rnd_get(col + 1, 7, (const uint32_t) (MT.rows - 1)) + 1) % MT.rows)) {
         om_A(MT, row, col) = 1;
       } else {
         om_A(MT, row, col) = 0;
       }
     }
     om_A(MT, row, col) = OCT_EXP[row];
   }
   return MT;
 }