nanorq: decode_phase1
decode_phase1()
static bool decode_phase1 (struct pparams * prm, octmat * A, octmat * X, octmat * D, uint16_vec c, uint16_t * i_val, uint16_t * u_val) static
Definition at line 161 of file precode.c.
References chooser_add_tracking_pair(), chooser_clear(), chooser_non_zero(), chooser_pick(), octmat::cols, graph_free(), graph_new(), pparams::H, pparams::L, oaxpy(), oswapcol(), oswaprow(), pparams::P, octmat::rows, and pparams::S.
Referenced by precode_matrix_intermediate1().
{
   uint16_t i = 0;
   uint16_t u = prm->P;
   struct chooser ch = chooser_init(A->rows);
   for (uint16_t row = 0; row < A->rows; row++) {
     bool is_hdpc = (row >= prm->S && row < (prm->S + prm->H));
     size_t row_degree = 0;
     for (uint16_t col = 0; col < A->cols - u; col++) {
       row_degree += (uint8_t)(om_A(*A, row, col));
     }
     chooser_add_tracking_pair(&ch, is_hdpc, row_degree);
   }
   while (i + u < prm->L) {
     uint16_t sub_rows = A->rows - i;
     uint16_t sub_cols = A->cols - i - u;
     uint16_t chosen, non_zero;
     struct graph *G = graph_new(sub_cols);
     non_zero = chooser_non_zero(&ch, A, G, i, sub_rows, sub_cols);
     if (non_zero == sub_cols + 1) {
       chooser_clear(&ch);
       graph_free(G);
       *i_val = 0;
       *u_val = 0;
       return false;
     }
     chosen = chooser_pick(&ch, G, i, sub_rows, non_zero);
     if (chosen != 0) {
       oswaprow(om_P(*A), i, chosen + i, A->cols);
       oswaprow(om_P(*X), i, chosen + i, X->cols);
       oswaprow(om_P(*D), i, chosen + i, D->cols);
       kv_swap(struct tracking_pair, ch.tracking, i, chosen + i);
     }
     if (om_A(*A, i, i) == 0) {
       uint16_t idx = 1;
       for (; idx < sub_cols; idx++) {
         if (om_A(*A, i, idx + i) != 0)
           break;
       }
       oswapcol(om_P(*A), i, i + idx, A->rows, A->cols);
       oswapcol(om_P(*X), i, i + idx, X->rows, X->cols);
       kv_swap(uint16_t, c, i, i + idx);
     }
     uint16_t col = (uint16_t) (sub_cols - 1);
     uint16_t swap = 1;
     for (; col > sub_cols - non_zero; col--) {
       if (om_A(*A, i, col + i) != 0)
         continue;
       while (swap < col && om_A(*A, i, swap + i) == 0) {
         swap++;
       }
       if (swap >= col)
         break;
       oswapcol(om_P(*A), col + i, swap + i, A->rows, A->cols);
       oswapcol(om_P(*X), col + i, swap + i, X->rows, X->cols);
       kv_swap(uint16_t, c, col + i, swap + i);
     }
     for (uint16_t row = 1; row < sub_rows; row++) {
       if (om_A(*A, row + i, i) != 0) {
         uint8_t mnum = om_A(*A, row + i, i);
         uint8_t mden = om_A(*A, i, i);
         uint8_t multiple = (uint8_t) ((mnum > 0 && mden > 0) ? OCTET_DIV(mnum, mden) : 0);
         if (multiple == 0)
           continue;
         oaxpy(om_P(*A), om_P(*A), row + i, i, A->cols, multiple);
         oaxpy(om_P(*D), om_P(*D), row + i, i, D->cols, multiple);
       }
     }
     i++;
     u += non_zero - 1;
     graph_free(G);
   }
   chooser_clear(&ch);
   *i_val = i;
   *u_val = u;
   return true;
 }