nanorq: nanorq_encode_cleanup
nanorq_encode_cleanup()
void nanorq_encode_cleanup (nanorq * rq, uint8_t sbn)
Definition at line 456 of file nanorq.c.
References nanorq::encoders, om_destroy(), encoder_core::sbn, and encoder_core::symbolmat.
Referenced by dump_block(), and nanorq_free().
{
     if (rq->encoders[sbn]) {
         struct encoder_core *enc = rq->encoders[sbn];
         om_destroy(&enc->symbolmat);
         free(enc);
         rq->encoders[sbn] = NULL;
     }
 }