nanorq: nanorq_decoder_add_symbol
nanorq_decoder_add_symbol()
bool nanorq_decoder_add_symbol (nanorq * rq, void * data, uint32_t fid)
Definition at line 487 of file nanorq.c.
References bitmask_check(), bitmask_gaps(), bitmask_set(), octmat::cols, repair_sym::esi, kv_push, decoder_core::mask, nanorq_block_decoder(), decoder_core::num_symbols, OM_INITIAL, om_R, om_resize(), decoder_core::repair_bin, repair_sym::row, decoder_core::sbn, and decoder_core::symbolmat.
Referenced by main().
{
     uint8_t sbn = (uint8_t) (fid >> 24);
     uint32_t esi = (fid & 0x00ffffff);
     struct decoder_core *dec = nanorq_block_decoder(rq, sbn);
     if (dec == NULL)
         return false;
     uint16_t cols = dec->symbolmat.cols;
     if (esi >= (1 << 20))
         return false;
     if (bitmask_gaps(dec->mask, dec->num_symbols) == 0) {
         return true; // no gaps! no repair needed.
     }
     if (bitmask_check(dec->mask, esi))
         return true; // already got this esi
     if (esi < dec->num_symbols) {
         memcpy(om_R(dec->symbolmat, esi), data, cols);
     } else {
         struct repair_sym rs = {esi, OM_INITIAL};
         om_resize(&rs.row, 1, cols);
         memcpy(om_R(rs.row, 0), data, cols);
         kv_push(struct repair_sym, dec->repair_bin, rs);
     }
     bitmask_set(dec->mask, esi);
     return true;
 }